#!/bin/sh

# Dual monitor setup; I'm positive there's a nicer way to do this but, well, it works for my needs
bspc monitor DVI-I-3 -n I
bspc monitor DVI-I-2 -n II
bspc monitor I -f
bspc desktop Desktop1 -n 1
bspc monitor -a 3 5 7
bspc monitor II -f
bspc desktop Desktop2 -n 2
bspc monitor -a 4 6 8
bspc desktop -f 1

# Single monitor setup
#bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width			3
bspc config window_gap				8
bspc config split_ratio				0.5
bspc config growth_factor			1.5
bspc config top_padding 			16
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focused_border_color	"#6BB283"
bspc config normal_border_color		"#C0696D"

bspc control --put-status
bspc control --subscribe > "$PANEL_FIFO" &
bspc config rule_command "$HOME/bin/rule_command"
$HOME/.config/bspwm/bspwm_rules
