#!/bin/sh

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="\\br\\f3$(echo ${line#?} | sed 's/|/\\f7|\\f3/g')"
            ;;
        T*)
            # xtitle output; two 1920x1080 screens
            title="\\br\\f7${line:1:290}"
            # xtitle output; one 1600x900 screen
            # title="\\br\\f7${line:1:90}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos \\u3\\br\\fr${name}\\ur"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos \\u4\\br\\f7${name}\\ur"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos \\u9\\br\\fr${name}\\ur"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos \\br\\fr${name}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos \\br\\f7${name}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\b1\\fr${name}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos    \\br\\f6$layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    # spacing designed for two 1920x1080 screens
    printf "%-500s%s\n" "\\l $wm_infos      $title" "$sys_infos"
    # spacing designed for one 1600x900 screen
    # printf "%-190s  %s\n" "\\l $wm_infos      $title" "$sys_infos"
done
